inherit_from: https://raw.githubusercontent.com/decidim/decidim/release/0.26-stable/.rubocop.yml

AllCops:
  Include:
    - "**/*.rb"
    - "**/*.rake"
    - "**/*.ru"
    - "**/Gemfile"
    - "**/Rakefile"
  Exclude:
    - "node_modules/**/*"
    - "db/schema.rb"
    - "vendor/**/*"
    - "development_app/**/*"
    - "spec/decidim_dummy_app/**/*"
    - "bin/**/*"
